"""

Revision ID: 05323a1c7eb9
Revises: 4a51e09115aa
Create Date: 2026-02-04 20:29:16.721900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05323a1c7eb9"
down_revision: Union[str, Sequence[str], None] = "4a51e09115aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_fan",
        sa.Column("from_uid", sa.BigInteger(), nullable=False, comment="关注者id"),
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="关注对象id"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="关注状态"),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_fan")),
        sa.UniqueConstraint("from_uid", "to_uid", name="uq_fan_from_to"),
    )
    op.create_table(
        "user_follow",
        sa.Column("from_uid", sa.BigInteger(), nullable=False, comment="关注者id"),
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="关注对象id"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="关注状态"),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_follow")),
        sa.UniqueConstraint("from_uid", "to_uid", name="uq_follow_from_to"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_follow")
    op.drop_table("user_fan")
    # ### end Alembic commands ###
