"""

Revision ID: 059d67022893
Revises: 7f48045cdd69
Create Date: 2026-02-09 11:25:20.645124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "059d67022893"
down_revision: Union[str, Sequence[str], None] = "7f48045cdd69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_announce",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("state", sa.SmallInteger(), nullable=False),
        sa.Column(
            "target_users", sa.ARRAY(sa.String(length=50)), nullable=True, comment="目标用户"
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_announce")),
    )

    op.create_index("ix_sys_announce_state", "sys_announce", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sys_announce_state", table_name="sys_announce")
    op.drop_table("sys_announce")
    # ### end Alembic commands ###
