"""

Revision ID: 1323466d1bea
Revises: 05323a1c7eb9
Create Date: 2026-02-06 13:59:17.041557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1323466d1bea"
down_revision: Union[str, Sequence[str], None] = "05323a1c7eb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_remind_cursor",
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="送达者"),
        sa.Column("action", sa.SmallInteger(), nullable=False, comment="行为类型：`ActionEnum`"),
        sa.Column("cursor", sa.BigInteger(), nullable=False, comment="最新读取的游标"),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("to_uid", "action", name=op.f("pk_notification_remind_cursor")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_remind_cursor")
    # ### end Alembic commands ###
