"""

Revision ID: 21a6a372756e
Revises: a3d970fe8345
Create Date: 2026-01-20 14:31:24.557554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21a6a372756e"
down_revision: Union[str, Sequence[str], None] = "a3d970fe8345"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "anniversary",
        "event_time",
        existing_type=postgresql.TIME(timezone=True),
        nullable=True,
        existing_comment="纪念日时间",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "anniversary",
        "event_time",
        existing_type=postgresql.TIME(timezone=True),
        nullable=False,
        existing_comment="纪念日时间",
    )
    # ### end Alembic commands ###
