"""

Revision ID: 22828a5d579a
Revises: 21a6a372756e
Create Date: 2026-01-20 14:41:01.572995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "22828a5d579a"
down_revision: Union[str, Sequence[str], None] = "21a6a372756e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anniversary", sa.Column("tz", sa.String(length=64), nullable=False))
    op.alter_column(
        "anniversary",
        "event_time",
        existing_type=postgresql.TIME(timezone=True),
        type_=sa.Time(),
        existing_comment="纪念日时间",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "anniversary",
        "event_time",
        existing_type=sa.Time(),
        type_=postgresql.TIME(timezone=True),
        existing_comment="纪念日时间",
        existing_nullable=True,
    )
    op.drop_column("anniversary", "tz")
    # ### end Alembic commands ###
