"""

Revision ID: 2f1f10d1a34b
Revises: 059d67022893
Create Date: 2026-02-09 14:20:28.462720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f1f10d1a34b"
down_revision: Union[str, Sequence[str], None] = "059d67022893"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_interaction",
        sa.Column("owner_uid", sa.BigInteger(), nullable=True, comment="资源作者id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_interaction", "owner_uid")
    # ### end Alembic commands ###
