"""

Revision ID: 4a51e09115aa
Revises: b6d9b4bf53e2
Create Date: 2026-01-29 12:48:43.873866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a51e09115aa"
down_revision: Union[str, Sequence[str], None] = "b6d9b4bf53e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invite",
        "token",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_comment="邮件链接里携带",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invite",
        "token",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_comment="邮件链接里携带",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
