"""

Revision ID: 51b4e3df0d27
Revises: 1323466d1bea
Create Date: 2026-02-07 15:12:08.623129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51b4e3df0d27"
down_revision: Union[str, Sequence[str], None] = "1323466d1bea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_announce",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=True, comment="优先级"),
        sa.Column(
            "scheduled_at", sa.DateTime(timezone=True), nullable=False, comment="计划发送时间"
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True, comment="实际发送时间"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="NtfyState"),
        sa.Column(
            "target_users", sa.ARRAY(sa.String(length=50)), nullable=True, comment="目标用户"
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_announce")),
    )
    op.create_index(
        "ix_sys_announce_status_scheduled", "sys_announce", ["state", "scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_sys_announce_sys_announce_scheduled_at"),
        "sys_announce",
        ["scheduled_at"],
        unique=False,
    )
    op.create_table(
        "sys_notification",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="送达者"),
        sa.Column("action", sa.SmallInteger(), nullable=False, comment="行为类型：`ActionEnum`"),
        sa.Column(
            "ttype", sa.SmallInteger(), nullable=False, comment="ResourceType目标对象资源类型"
        ),
        sa.Column("tid", sa.String(), nullable=False, comment="目标对象id"),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True, comment="实际发送时间"),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_notification")),
    )
    op.create_index(
        "ix_sys_notify_to_uid_action", "sys_notification", ["to_uid", "action"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sys_notify_to_uid_action", table_name="sys_notification")
    op.drop_table("sys_notification")
    op.drop_index(op.f("ix_sys_announce_sys_announce_scheduled_at"), table_name="sys_announce")
    op.drop_index("ix_sys_announce_status_scheduled", table_name="sys_announce")
    op.drop_table("sys_announce")
    # ### end Alembic commands ###
