"""Initial

Revision ID: 5b9d249f5da7
Revises:
Create Date: 2026-02-09 14:40:28.343894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b9d249f5da7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_notification",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="送达者"),
        sa.Column("action", sa.SmallInteger(), nullable=False, comment="行为类型：`ActionEnum`"),
        sa.Column(
            "ttype", sa.SmallInteger(), nullable=False, comment="ResourceType目标对象资源类型"
        ),
        sa.Column("tid", sa.String(), nullable=False, comment="目标对象id"),
        sa.Column("ttime", sa.Integer(), nullable=False, comment="事件触发时间"),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_notification")),
    )
    op.create_index(
        "ix_sys_notify_to_uid_action", "sys_notification", ["to_uid", "action"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sys_notify_to_uid_action", table_name="sys_notification")
    op.drop_table("sys_notification")
    # ### end Alembic commands ###
