"""

Revision ID: 620149e36c74
Revises: 
Create Date: 2025-12-05 14:24:10.798442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620149e36c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('post_key', sa.String(length=50), nullable=False),
    sa.Column('asset_type', sa.SmallInteger(), nullable=False, comment='资产类型'),
    sa.Column('asset_path', sa.String(), nullable=False, comment='资产路径'),
    sa.Column('state', sa.SmallInteger(), nullable=False, comment='状态'),
    sa.Column('create_by', sa.Integer(), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ctime', sa.Integer(), server_default=sa.text('EXTRACT(EPOCH FROM now())::int'), nullable=False),
    sa.Column('utime', sa.Integer(), server_default=sa.text('EXTRACT(EPOCH FROM now())::int'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_post_key'), 'asset', ['post_key'], unique=False)
    op.create_table('asset_sync_log',
    sa.Column('asset_id', sa.String(length=32), nullable=False, comment='资产ID'),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='服务器ID'),
    sa.Column('dest_path', sa.String(), nullable=False, comment='同步路径'),
    sa.Column('log_info', sa.String(), nullable=True, comment='日志'),
    sa.Column('state', sa.SmallInteger(), nullable=False, comment='同步状态'),
    sa.Column('ctime', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_sync_log_ctime', 'asset_sync_log', ['ctime'], unique=False)
    op.create_table('relay_post_records',
    sa.Column('post_key', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author_key', sa.String(length=50), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('post_thumbnail_url', sa.String(), nullable=True),
    sa.Column('post_thumbnail_hash', sa.String(length=50), nullable=True),
    sa.Column('local_image_path', sa.String(length=500), nullable=True),
    sa.Column('local_thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relay_post_records_author_key'), 'relay_post_records', ['author_key'], unique=False)
    op.create_index(op.f('ix_relay_post_records_post_key'), 'relay_post_records', ['post_key'], unique=False)
    op.create_table('server_asset',
    sa.Column('asset_id', sa.String(length=32), nullable=False, comment='资产ID'),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='服务器ID'),
    sa.Column('source_path', sa.String(), nullable=False, comment='源路径'),
    sa.Column('dest_path', sa.String(), nullable=False, comment='目标路径'),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ctime', sa.Integer(), server_default=sa.text('EXTRACT(EPOCH FROM now())::int'), nullable=False),
    sa.Column('utime', sa.Integer(), server_default=sa.text('EXTRACT(EPOCH FROM now())::int'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_server_state_asset_sid_aid', 'server_asset', ['state', 'server_id', 'asset_id'], unique=False)
    op.create_table('user',
    sa.Column('account', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='性别 0女 / 1男'),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('introduce', sa.String(length=100), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('ctime', sa.Integer(), server_default=sa.text('EXTRACT(EPOCH FROM now())::int'), nullable=False),
    sa.Column('utime', sa.Integer(), server_default=sa.text('EXTRACT(EPOCH FROM now())::int'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('ix_server_state_asset_sid_aid', table_name='server_asset')
    op.drop_table('server_asset')
    op.drop_index(op.f('ix_relay_post_records_post_key'), table_name='relay_post_records')
    op.drop_index(op.f('ix_relay_post_records_author_key'), table_name='relay_post_records')
    op.drop_table('relay_post_records')
    op.drop_index('ix_asset_sync_log_ctime', table_name='asset_sync_log')
    op.drop_table('asset_sync_log')
    op.drop_index(op.f('ix_asset_post_key'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
