"""

Revision ID: 7f48045cdd69
Revises: dc3d107e1c82
Create Date: 2026-02-07 21:43:04.665989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f48045cdd69"
down_revision: Union[str, Sequence[str], None] = "dc3d107e1c82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "sys_announce",
        "id",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.BigInteger(),
        postgresql_using="id::bigint",
        existing_nullable=False,
    )

    op.alter_column(
        "sys_notification",
        "id",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.BigInteger(),
        postgresql_using="id::bigint",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sys_notification",
        "id",
        existing_type=sa.BigInteger(),
        server_default=None,
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "sys_announce",
        "id",
        existing_type=sa.BigInteger(),
        server_default=None,
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
