"""

Revision ID: 987c4414638f
Revises:
Create Date: 2026-01-21 23:55:36.457663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "987c4414638f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anniversary",
        sa.Column("name", sa.String(length=50), nullable=False, comment="纪念日名称"),
        sa.Column("description", sa.Text(), nullable=True, comment="描述"),
        sa.Column("event_year", sa.Integer(), nullable=False, comment="纪念日年份"),
        sa.Column("event_date", sa.Date(), nullable=False, comment="纪念日日期"),
        sa.Column("event_time", sa.Time(), nullable=True, comment="纪念日时间"),
        sa.Column("tz", sa.String(length=64), nullable=False),
        sa.Column("cover", sa.String(length=255), nullable=True, comment="封面"),
        sa.Column("calendar_type", sa.SmallInteger(), nullable=False, comment="日历类型"),
        sa.Column("type", sa.SmallInteger(), nullable=False, comment="纪念日类型 AnniversaryType"),
        sa.Column("share_mode", sa.SmallInteger(), nullable=False, comment="0独享 1共享"),
        sa.Column(
            "owner_id",
            sa.BigInteger(),
            nullable=False,
            comment="纪念日归属者ID，拥有该纪念日所有权",
        ),
        sa.Column("is_reminder", sa.Boolean(), nullable=False, comment="是否提醒"),
        sa.Column("repeat_type", sa.SmallInteger(), nullable=False, comment="重复类型"),
        sa.Column("location", sa.String(length=100), nullable=True, comment="地点"),
        sa.Column("lunar_year", sa.Integer(), nullable=True),
        sa.Column("lunar_month", sa.SmallInteger(), nullable=True),
        sa.Column("lunar_day", sa.SmallInteger(), nullable=True),
        sa.Column("lunar_is_leap", sa.Boolean(), nullable=True, comment="是否闰月"),
        sa.Column(
            "next_trigger_at", sa.DateTime(timezone=True), nullable=False, comment="下一次触发时间"
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("create_by", sa.BigInteger(), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.BigInteger(), nullable=False, comment="更新人"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态 1启用 0禁用 -1删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anniversary")),
    )
    op.create_index(
        op.f("ix_anniversary_anniversary_next_trigger_at"),
        "anniversary",
        ["next_trigger_at"],
        unique=False,
    )
    op.create_index(
        "ix_state_uid_date", "anniversary", ["state", "owner_id", "event_date"], unique=False
    )
    op.create_table(
        "anniversary_media",
        sa.Column("anniv_id", sa.String(length=32), nullable=False, comment="纪念日ID"),
        sa.Column("media_id", sa.String(length=32), nullable=False, comment="媒体ID"),
        sa.Column("sort", sa.SmallInteger(), nullable=False, comment="排序号"),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("anniv_id", "media_id", name=op.f("pk_anniversary_media")),
    )
    op.create_table(
        "anniversary_member",
        sa.Column("anniv_id", sa.String(length=32), nullable=False, comment="纪念日ID"),
        sa.Column("ttype", sa.SmallInteger(), nullable=False, comment="目标类型 1 group 2 member"),
        sa.Column(
            "tid", sa.String(length=32), nullable=False, comment="目标对象ID，可以是group或member"
        ),
        sa.Column("role", sa.SmallInteger(), nullable=False, comment="角色GroupRole"),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anniversary_member")),
        sa.UniqueConstraint(
            "anniv_id", "ttype", "tid", name="uq_anniversary_member_anniv_idttypetid"
        ),
    )
    op.create_table(
        "anniversary_tag",
        sa.Column("anniv_id", sa.String(length=32), nullable=False, comment="纪念日ID"),
        sa.Column("tag_id", sa.String(length=32), nullable=False, comment="标签ID"),
        sa.PrimaryKeyConstraint("anniv_id", "tag_id", name=op.f("pk_anniversary_tag")),
    )
    op.create_table(
        "comment",
        sa.Column("parent_id", sa.BigInteger(), nullable=False, comment="父评论id"),
        sa.Column("root_id", sa.BigInteger(), nullable=False, comment="根评论id"),
        sa.Column("rtype", sa.SmallInteger(), nullable=False, comment="评论的资源类型"),
        sa.Column("rid", sa.String(length=32), nullable=False, comment="评论的资源id"),
        sa.Column("content", sa.Text(), nullable=True, comment="评论内容"),
        sa.Column("from_uid", sa.BigInteger(), nullable=False, comment="评论者"),
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="被评论者"),
        sa.Column("like_cnt", sa.Integer(), nullable=True, comment="点赞数"),
        sa.Column("dlike_cnt", sa.Integer(), nullable=True, comment="点踩数"),
        sa.Column("reply_cnt", sa.Integer(), nullable=True, comment="回复数"),
        sa.Column("ip", sa.String(length=40), nullable=True, comment="ip地址"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态 CommentState"),
        sa.Column("score", sa.DECIMAL(precision=14, scale=6), nullable=True, comment="热度值"),
        sa.Column("is_top", sa.Boolean(), nullable=False, comment="是否置顶"),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment")),
    )
    op.create_index(op.f("ix_comment_comment_from_uid"), "comment", ["from_uid"], unique=False)
    op.create_index(op.f("ix_comment_comment_parent_id"), "comment", ["parent_id"], unique=False)
    op.create_index(op.f("ix_comment_comment_to_uid"), "comment", ["to_uid"], unique=False)
    op.create_index(
        "ix_comment_rtype_rid_ctime", "comment", ["rtype", "rid", "ctime"], unique=False
    )
    op.create_table(
        "invite",
        sa.Column(
            "ttype", sa.SmallInteger(), nullable=False, comment="目标对象类型InviteTargetType"
        ),
        sa.Column("tid", sa.String(), nullable=False, comment="目标对象ID"),
        sa.Column("inviter_id", sa.BigInteger(), nullable=False),
        sa.Column("invitee_email", sa.String(length=100), nullable=True),
        sa.Column("invitee_user_id", sa.BigInteger(), nullable=True, comment="邀请用户ID"),
        sa.Column("token", sa.String(length=64), nullable=False, comment="邮件链接里携带"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="InviteState"),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message", sa.Text(), nullable=True, comment="邀请邮件内容"),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="存元数据，如角色/权限/邀请来源等额外信息",
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invite")),
    )
    op.create_index(
        op.f("ix_invite_invite_invitee_email"), "invite", ["invitee_email"], unique=False
    )
    op.create_index(
        op.f("ix_invite_invite_invitee_user_id"), "invite", ["invitee_user_id"], unique=False
    )
    op.create_index(op.f("ix_invite_invite_inviter_id"), "invite", ["inviter_id"], unique=False)
    op.create_index(op.f("ix_invite_invite_tid"), "invite", ["tid"], unique=False)
    op.create_index(op.f("ix_invite_invite_token"), "invite", ["token"], unique=True)
    op.create_table(
        "media",
        sa.Column("type", sa.SmallInteger(), nullable=False, comment="媒体类型: `MediaType`"),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
        sa.UniqueConstraint("path", name=op.f("uq_media_path")),
    )
    op.create_index(op.f("ix_media_media_state"), "media", ["state"], unique=False)
    op.create_table(
        "notification_remind",
        sa.Column("from_uid", sa.BigInteger(), nullable=False, comment="触发者"),
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="送达者"),
        sa.Column("action", sa.SmallInteger(), nullable=False, comment="行为类型：`ActionEnum`"),
        sa.Column(
            "ttype", sa.SmallInteger(), nullable=False, comment="ResourceType目标对象资源类型"
        ),
        sa.Column("tid", sa.String(), nullable=False, comment="目标对象id"),
        sa.Column("ttime", sa.Integer(), nullable=False, comment="事件触发时间"),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_remind")),
    )
    op.create_index(
        "notification_remind_to_uid_action",
        "notification_remind",
        ["to_uid", "action"],
        unique=False,
    )
    op.create_table(
        "reminder_rule",
        sa.Column("anniv_id", sa.String(length=32), nullable=False, comment="纪念日ID"),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column(
            "channels", sa.ARRAY(sa.SmallInteger()), nullable=False, comment="ReminderChannel列表"
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_rule")),
        sa.UniqueConstraint("anniv_id", "user_id", name=op.f("uq_reminder_rule_anniv_id_user_id")),
    )
    op.create_index(
        op.f("ix_reminder_rule_reminder_rule_anniv_id"), "reminder_rule", ["anniv_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminder_rule_reminder_rule_user_id"), "reminder_rule", ["user_id"], unique=False
    )
    op.create_table(
        "reminder_slot",
        sa.Column("rule_id", sa.String(length=32), nullable=True, comment="提醒规则ID"),
        sa.Column(
            "offset_days",
            sa.Integer(),
            nullable=False,
            comment="负数代表提前, 正数代表推后, 0表示当天",
        ),
        sa.Column("trigger_time", sa.Time(), nullable=False),
        sa.Column(
            "next_trigger_at", sa.DateTime(timezone=True), nullable=True, comment="下次触发时间"
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_slot")),
        sa.UniqueConstraint(
            "rule_id", "offset_days", "trigger_time", name="uq_reminder_slot_dedup"
        ),
    )
    op.create_table(
        "settings",
        sa.Column("name", sa.String(length=100), nullable=False, comment="设置唯一名称"),
        sa.Column("label", sa.String(length=50), nullable=False, comment="设置显示名称"),
        sa.Column("value", sa.String(length=255), nullable=False, comment="设置值"),
        sa.Column("description", sa.String(length=100), nullable=True, comment="描述"),
        sa.Column("group", sa.String(length=20), nullable=False, comment="设置分组 SettingsGroup"),
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("create_by", sa.BigInteger(), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.BigInteger(), nullable=False, comment="更新人"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态 1启用 0禁用 -1删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("name", name=op.f("uq_settings_name")),
    )
    op.create_table(
        "share_group",
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False, comment="共享组名称"),
        sa.Column("description", sa.String(length=100), nullable=True, comment="描述"),
        sa.Column("cover", sa.String(length=255), nullable=True, comment="封面"),
        sa.Column("max_members", sa.Integer(), nullable=False, comment="最大成员数"),
        sa.Column("is_public", sa.SmallInteger(), nullable=False, comment="0私密 1公开"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("create_by", sa.BigInteger(), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.BigInteger(), nullable=False, comment="更新人"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_group")),
    )
    op.create_index(op.f("ix_share_group_share_group_name"), "share_group", ["name"], unique=False)
    op.create_index(
        op.f("ix_share_group_share_group_owner_id"), "share_group", ["owner_id"], unique=False
    )
    op.create_table(
        "share_group_member",
        sa.Column("group_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.SmallInteger(), nullable=False, comment="GroupRole"),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("pk_share_group_member")),
    )
    op.create_table(
        "sys_notification",
        sa.Column("reminder_rule_id", sa.String(length=32), nullable=False, comment="提醒规则ID"),
        sa.Column(
            "scheduled_at", sa.DateTime(timezone=True), nullable=False, comment="计划发送时间"
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True, comment="实际发送时间"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="NtfyState"),
        sa.Column(
            "provider",
            sa.String(length=32),
            nullable=False,
            comment="提供商, 如aliyun, twilio, smtp",
        ),
        sa.Column("provider_msg_id", sa.String(length=128), nullable=True, comment="提供商消息ID"),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_notification")),
    )
    op.create_index(
        "ix_notify_status_scheduled", "sys_notification", ["state", "scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_sys_notification_sys_notification_reminder_rule_id"),
        "sys_notification",
        ["reminder_rule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_notification_sys_notification_scheduled_at"),
        "sys_notification",
        ["scheduled_at"],
        unique=False,
    )
    op.create_table(
        "tag",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("create_by", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态 1启用 0禁用 -1删除"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
        sa.UniqueConstraint("name", name=op.f("uq_tag_name")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True, start=10000001), nullable=False),
        sa.Column("account", sa.String(length=20), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("gender", sa.SmallInteger(), nullable=True, comment="性别 0女 / 1男"),
        sa.Column("birth", sa.Date(), nullable=True),
        sa.Column("phone", sa.String(length=15), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=20), nullable=True),
        sa.Column("introduce", sa.String(length=100), nullable=True),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("account", name=op.f("uq_user_account")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_user_phone")),
    )
    op.create_table(
        "user_device",
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column("device_id", sa.String(length=32), nullable=False, comment="设备ID"),
        sa.Column("device_type", sa.SmallInteger(), nullable=False, comment="设备类型"),
        sa.Column("device_token", sa.String(length=255), nullable=False, comment="设备Token"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_device")),
    )
    op.create_table(
        "user_interaction",
        sa.Column("action", sa.SmallInteger(), nullable=False, comment="行为，UserInterActionEnum"),
        sa.Column("rid", sa.String(length=36), nullable=False, comment="资源id"),
        sa.Column("rtype", sa.SmallInteger(), nullable=False, comment="资源类型 ResourceType"),
        sa.Column("uid", sa.BigInteger(), nullable=False, comment="用户id"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态：1收藏 0取消收藏"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_interaction")),
        sa.UniqueConstraint(
            "action", "rtype", "rid", "uid", name="uq_user_interaction_action_rtype_rid_uid"
        ),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column("settings_id", sa.Integer(), nullable=False, comment="设置ID SettingsModel.id"),
        sa.Column("value", sa.String(), nullable=True, comment="设置值, 默认为settings.value"),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "settings_id", name=op.f("pk_user_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_settings")
    op.drop_table("user_interaction")
    op.drop_table("user_device")
    op.drop_table("user")
    op.drop_table("tag")
    op.drop_index(
        op.f("ix_sys_notification_sys_notification_scheduled_at"), table_name="sys_notification"
    )
    op.drop_index(
        op.f("ix_sys_notification_sys_notification_reminder_rule_id"), table_name="sys_notification"
    )
    op.drop_index("ix_notify_status_scheduled", table_name="sys_notification")
    op.drop_table("sys_notification")
    op.drop_table("share_group_member")
    op.drop_index(op.f("ix_share_group_share_group_owner_id"), table_name="share_group")
    op.drop_index(op.f("ix_share_group_share_group_name"), table_name="share_group")
    op.drop_table("share_group")
    op.drop_table("settings")
    op.drop_table("reminder_slot")
    op.drop_index(op.f("ix_reminder_rule_reminder_rule_user_id"), table_name="reminder_rule")
    op.drop_index(op.f("ix_reminder_rule_reminder_rule_anniv_id"), table_name="reminder_rule")
    op.drop_table("reminder_rule")
    op.drop_index("notification_remind_to_uid_action", table_name="notification_remind")
    op.drop_table("notification_remind")
    op.drop_index(op.f("ix_media_media_state"), table_name="media")
    op.drop_table("media")
    op.drop_index(op.f("ix_invite_invite_token"), table_name="invite")
    op.drop_index(op.f("ix_invite_invite_tid"), table_name="invite")
    op.drop_index(op.f("ix_invite_invite_inviter_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_invite_invitee_user_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_invite_invitee_email"), table_name="invite")
    op.drop_table("invite")
    op.drop_index("ix_comment_rtype_rid_ctime", table_name="comment")
    op.drop_index(op.f("ix_comment_comment_to_uid"), table_name="comment")
    op.drop_index(op.f("ix_comment_comment_parent_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_comment_from_uid"), table_name="comment")
    op.drop_table("comment")
    op.drop_table("anniversary_tag")
    op.drop_table("anniversary_member")
    op.drop_table("anniversary_media")
    op.drop_index("ix_state_uid_date", table_name="anniversary")
    op.drop_index(op.f("ix_anniversary_anniversary_next_trigger_at"), table_name="anniversary")
    op.drop_table("anniversary")
    # ### end Alembic commands ###
