"""add anniversary

Revision ID: a9b40e9a2fd2
Revises: efd1f13c7e1c
Create Date: 2026-01-08 16:19:53.953964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a9b40e9a2fd2"
down_revision: Union[str, Sequence[str], None] = "efd1f13c7e1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anniversary_member",
        sa.Column("anniv_id", sa.String(length=32), nullable=False, comment="纪念日ID"),
        sa.Column("ttype", sa.SmallInteger(), nullable=False, comment="目标类型 1 group 2 member"),
        sa.Column(
            "tid", sa.String(length=32), nullable=False, comment="目标对象ID，可以是group或member"
        ),
        sa.Column("role", sa.SmallInteger(), nullable=False, comment="角色GroupRole"),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("create_by", sa.BigInteger(), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.BigInteger(), nullable=False, comment="更新人"),
        sa.PrimaryKeyConstraint("anniv_id", "ttype", "tid"),
        sa.UniqueConstraint("anniv_id", "ttype", "tid", name="uq_anniv_member_dedup"),
    )
    op.create_table(
        "anniversary_tag",
        sa.Column("anniv_id", sa.String(length=32), nullable=False, comment="纪念日ID"),
        sa.Column("tag_id", sa.String(length=32), nullable=False, comment="标签ID"),
        sa.PrimaryKeyConstraint("anniv_id", "tag_id"),
    )
    op.create_table(
        "invite",
        sa.Column(
            "ttype", sa.SmallInteger(), nullable=False, comment="目标对象类型InviteTargetType"
        ),
        sa.Column("tid", sa.String(), nullable=False, comment="目标对象ID"),
        sa.Column("inviter_id", sa.BigInteger(), nullable=False),
        sa.Column("invitee_email", sa.String(length=320), nullable=False),
        sa.Column("invitee_user_id", sa.BigInteger(), nullable=True, comment="邀请用户ID"),
        sa.Column("token", sa.String(length=64), nullable=False, comment="邮件链接里携带"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="InviteState"),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message", sa.Text(), nullable=True, comment="邀请邮件内容"),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="存元数据，如角色/权限/邀请来源等额外信息",
        ),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invite_invitee_email"), "invite", ["invitee_email"], unique=False)
    op.create_index(op.f("ix_invite_invitee_user_id"), "invite", ["invitee_user_id"], unique=False)
    op.create_index(op.f("ix_invite_inviter_id"), "invite", ["inviter_id"], unique=False)
    op.create_index(op.f("ix_invite_tid"), "invite", ["tid"], unique=False)
    op.create_index(op.f("ix_invite_token"), "invite", ["token"], unique=True)
    op.create_table(
        "notification_remind",
        sa.Column("from_uid", sa.BigInteger(), nullable=False, comment="触发者"),
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="送达者"),
        sa.Column("action", sa.SmallInteger(), nullable=False, comment="行为类型：`ActionEnum`"),
        sa.Column(
            "ttype",
            sa.String(length=20),
            nullable=False,
            comment="NtfyResourceType目标对象资源类型",
        ),
        sa.Column("tid", sa.String(), nullable=False, comment="目标对象id"),
        sa.Column("cursor", sa.BigInteger(), nullable=False, comment="最新读取的游标"),
        sa.Column("ttime", sa.Integer(), nullable=False, comment="事件触发时间"),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "notification_remind_to_uid_action",
        "notification_remind",
        ["to_uid", "action"],
        unique=False,
    )
    op.create_table(
        "reminder_rule",
        sa.Column("anniv_id", sa.String(length=32), nullable=False, comment="纪念日ID"),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column("channel", sa.SmallInteger(), nullable=False, comment="ReminderChannel"),
        sa.Column("days_before", sa.Integer(), nullable=False),
        sa.Column("trigger_time", sa.Time(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("next_trigger_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "anniv_id",
            "user_id",
            "channel",
            "days_before",
            "trigger_time",
            name="uq_reminder_rule_dedup",
        ),
    )
    op.create_index(
        "ix_reminder_enabled_next", "reminder_rule", ["enabled", "next_trigger_at"], unique=False
    )
    op.create_index(op.f("ix_reminder_rule_anniv_id"), "reminder_rule", ["anniv_id"], unique=False)
    op.create_index(
        op.f("ix_reminder_rule_next_trigger_at"), "reminder_rule", ["next_trigger_at"], unique=False
    )
    op.create_index(op.f("ix_reminder_rule_user_id"), "reminder_rule", ["user_id"], unique=False)
    op.create_table(
        "settings",
        sa.Column("name", sa.String(length=50), nullable=False, comment="设置名称"),
        sa.Column("value", sa.String(length=255), nullable=False, comment="设置值"),
        sa.Column("description", sa.String(length=100), nullable=True, comment="描述"),
        sa.Column("group", sa.String(length=20), nullable=False, comment="设置分组 SettingsGroup"),
        sa.Column("type", sa.SmallInteger(), nullable=False, comment="设置类型 SettingsType"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("create_by", sa.BigInteger(), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.BigInteger(), nullable=False, comment="更新人"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态 1启用 0禁用 -1删除"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "share_group",
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False, comment="共享组名称"),
        sa.Column("description", sa.String(length=100), nullable=True, comment="描述"),
        sa.Column("cover", sa.String(length=255), nullable=True, comment="封面"),
        sa.Column("max_members", sa.SmallInteger(), nullable=False, comment="最大成员数"),
        sa.Column("is_public", sa.SmallInteger(), nullable=False, comment="0私密 1公开"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("create_by", sa.BigInteger(), nullable=False, comment="创建人"),
        sa.Column("update_by", sa.BigInteger(), nullable=False, comment="更新人"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_share_group_owner_id"), "share_group", ["owner_id"], unique=False)
    op.create_table(
        "share_group_member",
        sa.Column("group_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.SmallInteger(), nullable=False, comment="GroupRole"),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", "id"),
    )
    op.create_index("ix_share_group_member_user", "share_group_member", ["user_id"], unique=False)
    op.create_table(
        "sys_notification",
        sa.Column("reminder_rule_id", sa.String(length=32), nullable=False, comment="提醒规则ID"),
        sa.Column(
            "scheduled_at", sa.DateTime(timezone=True), nullable=False, comment="计划发送时间"
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True, comment="实际发送时间"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="NtfyState"),
        sa.Column(
            "provider",
            sa.String(length=32),
            nullable=False,
            comment="提供商, 如aliyun, twilio, smtp",
        ),
        sa.Column("provider_msg_id", sa.String(length=128), nullable=True, comment="提供商消息ID"),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notify_status_scheduled", "sys_notification", ["state", "scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_sys_notification_reminder_rule_id"),
        "sys_notification",
        ["reminder_rule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sys_notification_scheduled_at"), "sys_notification", ["scheduled_at"], unique=False
    )
    op.create_table(
        "tag",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("create_by", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态 1启用 0禁用 -1删除"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_device",
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column("device_id", sa.String(length=32), nullable=False, comment="设备ID"),
        sa.Column("device_type", sa.SmallInteger(), nullable=False, comment="设备类型"),
        sa.Column("device_token", sa.String(length=255), nullable=False, comment="设备Token"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column("settings_id", sa.Integer(), nullable=False, comment="设置ID SettingsModel.id"),
        sa.Column("value", sa.String(), nullable=True, comment="设置值, 默认为settings.value"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "anniversary", sa.Column("event_date", sa.Date(), nullable=False, comment="纪念日日期")
    )
    op.add_column(
        "anniversary", sa.Column("event_time", sa.DateTime(), nullable=False, comment="纪念日时间")
    )
    op.add_column(
        "anniversary",
        sa.Column("calendar_type", sa.SmallInteger(), nullable=False, comment="日历类型"),
    )
    op.add_column(
        "anniversary",
        sa.Column("share_mode", sa.SmallInteger(), nullable=False, comment="0独享 1共享"),
    )
    op.add_column(
        "anniversary",
        sa.Column(
            "owner_id",
            sa.BigInteger(),
            nullable=False,
            comment="纪念日归属者ID，拥有该纪念日所有权",
        ),
    )
    op.add_column(
        "anniversary", sa.Column("is_reminder", sa.Boolean(), nullable=False, comment="是否提醒")
    )
    op.add_column(
        "anniversary",
        sa.Column("repeat_type", sa.SmallInteger(), nullable=False, comment="重复类型"),
    )
    op.add_column(
        "anniversary", sa.Column("create_by", sa.BigInteger(), nullable=False, comment="创建人")
    )
    op.add_column(
        "anniversary", sa.Column("update_by", sa.BigInteger(), nullable=False, comment="更新人")
    )
    op.add_column(
        "anniversary",
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态 1启用 0禁用 -1删除"),
    )
    op.alter_column(
        "anniversary",
        "name",
        existing_type=sa.VARCHAR(length=50),
        comment="纪念日名称",
        existing_nullable=False,
    )
    op.alter_column(
        "anniversary",
        "description",
        existing_type=sa.VARCHAR(length=100),
        comment="描述",
        existing_nullable=True,
    )
    op.create_index(
        "idx_state_uid_date", "anniversary", ["state", "owner_id", "event_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_state_uid_date", table_name="anniversary")
    op.alter_column(
        "anniversary",
        "description",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="描述",
        existing_nullable=True,
    )
    op.alter_column(
        "anniversary",
        "name",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="纪念日名称",
        existing_nullable=False,
    )
    op.drop_column("anniversary", "state")
    op.drop_column("anniversary", "update_by")
    op.drop_column("anniversary", "create_by")
    op.drop_column("anniversary", "repeat_type")
    op.drop_column("anniversary", "is_reminder")
    op.drop_column("anniversary", "owner_id")
    op.drop_column("anniversary", "share_mode")
    op.drop_column("anniversary", "calendar_type")
    op.drop_column("anniversary", "event_time")
    op.drop_column("anniversary", "event_date")
    op.drop_table("user_settings")
    op.drop_table("user_device")
    op.drop_table("tag")
    op.drop_index(op.f("ix_sys_notification_scheduled_at"), table_name="sys_notification")
    op.drop_index(op.f("ix_sys_notification_reminder_rule_id"), table_name="sys_notification")
    op.drop_index("ix_notify_status_scheduled", table_name="sys_notification")
    op.drop_table("sys_notification")
    op.drop_index("ix_share_group_member_user", table_name="share_group_member")
    op.drop_table("share_group_member")
    op.drop_index(op.f("ix_share_group_owner_id"), table_name="share_group")
    op.drop_table("share_group")
    op.drop_table("settings")
    op.drop_index(op.f("ix_reminder_rule_user_id"), table_name="reminder_rule")
    op.drop_index(op.f("ix_reminder_rule_next_trigger_at"), table_name="reminder_rule")
    op.drop_index(op.f("ix_reminder_rule_anniv_id"), table_name="reminder_rule")
    op.drop_index("ix_reminder_enabled_next", table_name="reminder_rule")
    op.drop_table("reminder_rule")
    op.drop_index("notification_remind_to_uid_action", table_name="notification_remind")
    op.drop_table("notification_remind")
    op.drop_index(op.f("ix_invite_token"), table_name="invite")
    op.drop_index(op.f("ix_invite_tid"), table_name="invite")
    op.drop_index(op.f("ix_invite_inviter_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_invitee_user_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_invitee_email"), table_name="invite")
    op.drop_table("invite")
    op.drop_table("anniversary_tag")
    op.drop_table("anniversary_member")
    # ### end Alembic commands ###
