"""initial

Revision ID: cd3bd9d39409
Revises:
Create Date: 2026-01-01 13:26:07.041780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd3bd9d39409"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), sa.Identity(always=True, start=10000001), nullable=False),
        sa.Column("account", sa.String(length=20), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("gender", sa.SmallInteger(), nullable=True, comment="性别 0女 / 1男"),
        sa.Column("birth", sa.Date(), nullable=True),
        sa.Column("phone", sa.String(length=15), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=20), nullable=True),
        sa.Column("introduce", sa.String(length=100), nullable=True),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
