"""

Revision ID: d546722ea3d1
Revises: 5b9d249f5da7
Create Date: 2026-02-09 15:20:50.616156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d546722ea3d1"
down_revision: Union[str, Sequence[str], None] = "5b9d249f5da7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anniversary", sa.Column("collect_cnt", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "anniversary", sa.Column("like_cnt", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "anniversary", sa.Column("comment_cnt", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "anniversary", sa.Column("share_cnt", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anniversary", "share_cnt")
    op.drop_column("anniversary", "comment_cnt")
    op.drop_column("anniversary", "like_cnt")
    op.drop_column("anniversary", "collect_cnt")
    # ### end Alembic commands ###
