"""

Revision ID: dc3d107e1c82
Revises: 51b4e3df0d27
Create Date: 2026-02-07 15:16:07.333037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc3d107e1c82"
down_revision: Union[str, Sequence[str], None] = "51b4e3df0d27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sys_notification", sa.Column("ttime", sa.Integer(), nullable=False, comment="事件触发时间")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sys_notification", "ttime")
    # ### end Alembic commands ###
