"""

Revision ID: ec2832b6e928
Revises: 22828a5d579a
Create Date: 2026-01-20 22:02:32.414961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec2832b6e928"
down_revision: Union[str, Sequence[str], None] = "22828a5d579a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=False, comment="父评论id"),
        sa.Column("root_id", sa.BigInteger(), nullable=False, comment="根评论id"),
        sa.Column("rtype", sa.SmallInteger(), nullable=False, comment="评论的资源类型"),
        sa.Column("rid", sa.String(length=32), nullable=False, comment="评论的资源id"),
        sa.Column("content", sa.Text(), nullable=True, comment="评论内容"),
        sa.Column("from_uid", sa.BigInteger(), nullable=False, comment="评论者"),
        sa.Column("to_uid", sa.BigInteger(), nullable=False, comment="被评论者"),
        sa.Column("like_cnt", sa.Integer(), nullable=True, comment="点赞数"),
        sa.Column("dlike_cnt", sa.Integer(), nullable=True, comment="点踩数"),
        sa.Column("reply_cnt", sa.Integer(), nullable=True, comment="回复数"),
        sa.Column("ip", sa.String(length=40), nullable=True, comment="ip地址"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态 CommentState"),
        sa.Column("score", sa.DECIMAL(precision=14, scale=6), nullable=True, comment="热度值"),
        sa.Column("is_top", sa.Boolean(), nullable=False, comment="是否置顶"),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment")),
    )
    op.create_index(op.f("ix_comment_comment_from_uid"), "comment", ["from_uid"], unique=False)
    op.create_index(op.f("ix_comment_comment_parent_id"), "comment", ["parent_id"], unique=False)
    op.create_index(op.f("ix_comment_comment_to_uid"), "comment", ["to_uid"], unique=False)
    op.create_index(
        "ix_comment_rtype_rid_ctime", "comment", ["rtype", "rid", "ctime"], unique=False
    )
    op.create_table(
        "user_interaction",
        sa.Column("action", sa.SmallInteger(), nullable=False, comment="行为，UserInterActionEnum"),
        sa.Column("rid", sa.String(length=36), nullable=False, comment="资源id"),
        sa.Column("rtype", sa.SmallInteger(), nullable=False, comment="资源类型 ResourceType"),
        sa.Column("uid", sa.BigInteger(), nullable=False, comment="用户id"),
        sa.Column("state", sa.SmallInteger(), nullable=False, comment="状态：1收藏 0取消收藏"),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_interaction")),
        sa.UniqueConstraint(
            "action", "rtype", "rid", "uid", name="uq_user_interaction_action_rtype_rid_uid"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_interaction")
    op.drop_index("ix_comment_rtype_rid_ctime", table_name="comment")
    op.drop_index(op.f("ix_comment_comment_to_uid"), table_name="comment")
    op.drop_index(op.f("ix_comment_comment_parent_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_comment_from_uid"), table_name="comment")
    op.drop_table("comment")
    # ### end Alembic commands ###
