"""alter users

Revision ID: efd1f13c7e1c
Revises: cd3bd9d39409
Create Date: 2026-01-06 14:57:18.148382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efd1f13c7e1c"
down_revision: Union[str, Sequence[str], None] = "cd3bd9d39409"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anniversary",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "ctime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.Column(
            "utime",
            sa.Integer(),
            server_default=sa.text("EXTRACT(EPOCH FROM now())::int"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "user",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.Identity(
            always=True,
            start=10000001,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.Identity(
            always=True,
            start=10000001,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
    )
    op.drop_table("anniversary")
    # ### end Alembic commands ###
