"""Initial

Revision ID: fcdc95cb57da
Revises:
Create Date: 2026-02-09 14:38:51.990011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fcdc95cb57da"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sys_notification",
        "id",
        existing_type=sa.BIGINT(),
        server_default=sa.Identity(always=False),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sys_notification",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
